### ISSUE TITLE
Creation of collection version failed 

### ISSUE THREAD

**Issue by AnjaliWadhwa** [OpenConceptLab/ocl_web#115]
Tried to create version of collection with name 'V1', it failed with below error in logs. I tried with a different name like V1.1, or any other name which does not already exist across collections, it works.

```
[21/Sep/2016 08:45:33] "POST /users/awadhwa1/collections/WHO-testFk/versions/ HTTP/1.1" 500 100141
[21/Sep/2016 08:45:40] "GET /users/awadhwa1/collections/WHO-testFk/ HTTP/1.1" 200 1487
[21/Sep/2016 08:45:43] "GET /users/awadhwa1/collections/WHO-testFk/ HTTP/1.1" 200 1487
[21/Sep/2016 08:45:43] "GET /users/awadhwa1/collections/WHO-testFk/versions/?limit=10&verbose=true&page=1 HTTP/1.1" 200 1205
[21/Sep/2016 08:45:45] "GET /users/awadhwa1/collections/WHO-testFk/versions/?limit=1 HTTP/1.1" 200 224
[21/Sep/2016 08:45:45] "GET /users/awadhwa1/collections/WHO-testFk/ HTTP/1.1" 200 1487
[21/Sep/2016 08:45:54] "GET /users/awadhwa1/collections/WHO-testFk/versions/?limit=1 HTTP/1.1" 200 224
[21/Sep/2016 08:45:54] "POST /users/awadhwa1/collections/WHO-testFk/versions/ HTTP/1.1" 201 148
[21/Sep/2016 08:45:55] "GET /users/awadhwa1/collections/WHO-testFk/ HTTP/1.1" 200 1487
[21/Sep/2016 08:45:55] "GET /users/awadhwa1/collections/WHO-testFk/versions/?limit=10&verbose=true&page=1 HTTP/1.1" 200 2461
[21/Sep/2016 08:46:03] "GET /users/awadhwa1/collections/WHO-testFk/versions/?limit=1 HTTP/1.1" 200 224
[21/Sep/2016 08:46:03] "GET /users/awadhwa1/collections/WHO-testFk/ HTTP/1.1" 200 1487
[21/Sep/2016 08:46:09] "GET /users/awadhwa1/collections/WHO-testFk/versions/?limit=1 HTTP/1.1" 200 224
Internal Server Error: /users/awadhwa1/collections/WHO-testFk/versions/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 327, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 324, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/collection/views.py", line 191, in post
    return self.create(request, *args, **kwargs)
  File "/code/collection/views.py", line 199, in create
    self.object = serializer.save(force_insert=True, versioned_object=self.versioned_object)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 518, in save
    self.save_object(self.object, **kwargs)
  File "/code/collection/serializers.py", line 232, in save_object
    errors = CollectionVersion.persist_new(obj, user=request_user, **kwargs)
  File "/code/collection/models.py", line 248, in persist_new
    return cls.persist_changes(obj, **kwargs)
  File "/code/collection/models.py", line 255, in persist_changes
    return super(CollectionVersion, cls).persist_changes(obj, **kwargs)
  File "/code/oclapi/models.py", line 418, in persist_changes
    if not persisted:
UnboundLocalError: local variable 'persisted' referenced before assignment
```

<img width="1280" alt="screen shot 2016-09-21 at 18 23 00" src="https://cloud.githubusercontent.com/assets/3176602/18711635/7907de06-8028-11e6-982b-01995c3df170.png">

**Comment by paynejd** [comment]
Error handling still needs to be implemented for this -- if I create a repository version "v1" and then attempt to create another repository version with the same ID (in the same source) I get a big nasty error message:

![image](https://cloud.githubusercontent.com/assets/1189689/18834599/cc892414-83c4-11e6-9166-2c63243f29ac.png)

**Comment by paynejd** [comment]
Improved error handling was resolved on another ticket
